apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  namespace: demomongo
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  # persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongo