apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: demok8s
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 8080 # Expose the service on internal port 80
    targetPort: 80 # Container port 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: nginx
