apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: demok8s
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # จำนวน Pod ที่จะสร้างขึ้นมาเพิ่มเมื่อมีการอัพเดท
      maxUnavailable: 1 # จำนวน Pod ที่จะลดลงเมื่อมีการอัพเดท
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"