-- สร้างตาราง Product
CREATE TABLE Product (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  productname VARCHAR2(255) NOT NULL,
  price FLOAT NOT NULL,
  qty NUMBER NOT NULL,
  thumbnail VARCHAR2(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status NUMBER(1) NOT NULL -- ใน Oracle ไม่มี BOOLEAN ใช้ NUMBER(1) แทน (0 = FALSE, 1 = TRUE)
);

-- สร้าง trigger สำหรับการอัปเดต updated_at อัตโนมัติเมื่อมีการแก้ไขข้อมูล
CREATE OR REPLACE TRIGGER product_before_update
BEFORE UPDATE ON Product
FOR EACH ROW
BEGIN
  :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- เพิ่มข้อมูลสินค้า 5 รายการ
INSERT INTO Product (productname, price, qty, thumbnail, status) VALUES
('Product 1', 100.00, 10, 'https://example.com/image1.jpg', 1),
('Product 2', 200.00, 20, 'https://example.com/image2.jpg', 1),
('Product 3', 300.00, 30, 'https://example.com/image3.jpg', 1),
('Product 4', 400.00, 40, 'https://example.com/image4.jpg', 1),
('Product 5', 500.00, 50, 'https://example.com/image5.jpg', 1);
