apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
  selector:
    app: node-exporter